version: '3.3'
services:
  api:
    image: home-assignment-api
    container_name: home-assignment-api
    build:
      context: ./services/api
      dockerfile: ./Dockerfile
    command: sh -c "yarn start"
    ports:
      - "8080:8080"
    volumes:
      - ./services/api/src:/app/src
    depends_on:
      - mongodb
  service:
    image: home-assignment-service
    container_name: home-assignment-service
    build:
      context: ./services/service
      dockerfile: ./Dockerfile
    command: sh -c "crond -b -f"
    volumes:
      - ./services/service/src:/app/src
    depends_on:
      - mongodb
  mongodb:
    image: mongo:4.4.3
    container_name: home-assignment-db
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./dump:/dbdump